### ISSUE TITLE
Attempting to add extended context to the seq2seq model

### ISSUE THREAD

**Issue by Akamight** [bearpelican/musicautobot#10]
So I want to use the large seq2seq model to create some music, but then I found out that it is extremely memory consuming and I can only input a mere 16 bars into the network.

However, I have this idea that if I can input the next 32 bars into the decoder as the context, it might perform better since we are working with the Transformer-XL. But I've tried many ways to add it in and its either totally not working or at best yielding the exact same behaviour as before. So, is there a simple way to add this?

**Comment by bearpelican** [comment]
Just to clarify - you are using seq2seq for translation right? Sending 32 bars of melody to translate into chords or vice versa.

Yeah looks like it's super high memory because the decoder uses the full context of the encoder while using memory for storing what has already been predicted.

As you mentioned, we could try utilizing memory to store the encoder state (not just the decoder).
Right now, we're passing the [x_enc](https://github.com/bearpelican/musicautobot/blob/8fb9166a19aff66b2ade54728c4170c4b45a9619/musicautobot/multitask_transformer/learner.py#L175) on every iteration. Maybe you can try passing `x_enc` only on the first token prediction. Don't pass it in after that.

Ideally, x_enc will be stored in [mha2](https://github.com/bearpelican/musicautobot/blob/8fb9166a19aff66b2ade54728c4170c4b45a9619/musicautobot/multitask_transformer/model.py#L179) memory the second time around.

It's good that you pointed that out. I might try something next week, but if you figure it out beforehand, please let me know!

**Comment by bearpelican** [comment]
Turns out layer 2 memory was turned on when it shouldn't have been: eb95ea6. Turning it off gives a pretty significant speed boost. 

Let me know if that still doesn't work
