### ISSUE TITLE
Question about the Vocab

### ISSUE THREAD

**Issue by firedie** [bearpelican/musicautobot#18]
Hi,
Is there any chance you can add comment about the vocab token. Tokens like BOS, PAD are easy to understand, but  Tokens like CSEQ, MSEQ, NSCLS are quite confusing.
By the way, why you decide to use tokens inside of using pure digital number. In another way to ask this question, why not just using idxenc to feed the model but using the "textify token" to feed the model.

Cheers!

**Comment by bearpelican** [comment]
Hope this clears things up - f4a09d8264cf958a60b569eeadfc2acd3a43c4da

Not sure I understand the question.
Are you asking why we feed the model this:
`item.to_tensor()
Out: tensor([  0,   1,  81, 139,  61, 153,  57, 153,  54, 153,   8, 139,  80, 139,
          8, 139,  80, 139,   8, 139,  78, 139,   8, 139,  78, 139,   8, 139,
         76, 141,   8, 141,  73, 138,   8, 138,  71, 138], device='cuda:0')`

Instead of something like this?

# Text format:
`item.to_text()
Out: 'xxbos xxpad n72 d2 n52 d16 n48 d16 n45 d16 xxsep d2 n71 d2 xxsep d2 n71 d2 xxsep d2 n69 d2 xxsep d2 n69 d2 xxsep d2 n67 d4 xxsep d4 n64 d1 xxsep d1 n62 d1'`

**Comment by firedie** [comment]
ya, thats what am I asking
Sorry for the delay
