### ISSUE TITLE
Pretrained weights ? 

### ISSUE THREAD

**Issue by MoMe36** [bearpelican/musicautobot#2]
Thanks for the repo, this is really neat ! 
Any chances you release pretrained weights to download ? 

Thanks !

**Comment by bearpelican** [comment]
Thanks for checking it out!

Yup if you follow this [notebook](https://github.com/bearpelican/musicautobot/blob/master/notebooks/multitask_transformer/Generate.ipynb), it'll download the pre-trained model automatically.

Otherwise you can download them directly here:
https://ashaw-midi-web-server.s3-us-west-2.amazonaws.com/pretrained.tgz
